-- Drop all existing procedures

DROP PROCEDURE IF EXISTS departureTimeUpdate;
DROP PROCEDURE IF EXISTS addPassenger;
DROP PROCEDURE IF EXISTS newAirline;
DROP PROCEDURE IF EXISTS addNewFlight;
DROP PROCEDURE IF EXISTS cancelFlightByAdmin;
DROP PROCEDURE IF EXISTS changePlaneModel;
DROP PROCEDURE IF EXISTS addHourlyEmployee;
DROP PROCEDURE IF EXISTS addContractedEmployee;
DROP PROCEDURE IF EXISTS removingEmployee;
DROP PROCEDURE IF EXISTS removePassenger;
DROP PROCEDURE IF EXISTS viewFlightInfo;
DROP PROCEDURE IF EXISTS updateRunwayforEmployee;
DROP PROCEDURE IF EXISTS listPassByFlight;
DROP PROCEDURE IF EXISTS retrieveEmployee;
DROP PROCEDURE IF EXISTS retrieveRunways;
